from panda3d.core import Point3

HeadDict = {'dls': '/models/char/tt_a_chr_dgm_shorts_head_',
            'dss': '/models/char/tt_a_chr_dgm_skirt_head_',
            'dsl': '/models/char/tt_a_chr_dgs_shorts_head_',
            'dll': '/models/char/tt_a_chr_dgl_shorts_head_',
            'c': '/models/char/cat-heads-',
            'h': '/models/char/horse-heads-',
            'm': '/models/char/mouse-heads-',
            'r': '/models/char/rabbit-heads-',
            'f': '/models/char/duck-heads-',
            'p': '/models/char/monkey-heads-',
            'b': '/models/char/bear-heads-',
            's': '/models/char/pig-heads-'}
EyelashDict = {'d': '/models/char/dog-lashes',
               'c': '/models/char/cat-lashes',
               'h': '/models/char/horse-lashes',
               'm': '/models/char/mouse-lashes',
               'r': '/models/char/rabbit-lashes',
               'f': '/models/char/duck-lashes',
               'p': '/models/char/monkey-lashes',
               'b': '/models/char/bear-lashes',
               's': '/models/char/pig-lashes'}
DogMuzzleDict = {'dls': '/models/char/dogMM_Shorts-headMuzzles-',
                 'dss': '/models/char/dogMM_Skirt-headMuzzles-',
                 'dsl': '/models/char/dogSS_Shorts-headMuzzles-',
                 'dll': '/models/char/dogLL_Shorts-headMuzzles-'}
toonBodyScales = {'mouse': 0.6,
 'cat': 0.73,
 'duck': 0.66,
 'rabbit': 0.74,
 'horse': 0.85,
 'dog': 0.85,
 'monkey': 0.68,
 'bear': 0.85,
 'pig': 0.77}
toonHeadScales = {'mouse': Point3(1.0),
 'cat': Point3(1.0),
 'duck': Point3(1.0),
 'rabbit': Point3(1.0),
 'horse': Point3(1.0),
 'dog': Point3(1.0),
 'monkey': Point3(1.0),
 'bear': Point3(1.0),
 'pig': Point3(1.0)}
legHeightDict = {'s': 1.5,
 'm': 2.0,
 'l': 2.75}
torsoHeightDict = {'s': 1.5,
 'm': 1.75,
 'l': 2.25,
 'ss': 1.5,
 'ms': 1.75,
 'ls': 2.25,
 'sd': 1.5,
 'md': 1.75,
 'ld': 2.25}
headHeightDict = {'dls': 0.75,
 'dss': 0.5,
 'dsl': 0.5,
 'dll': 0.75,
 'cls': 0.75,
 'css': 0.5,
 'csl': 0.5,
 'cll': 0.75,
 'hls': 0.75,
 'hss': 0.5,
 'hsl': 0.5,
 'hll': 0.75,
 'mls': 0.75,
 'mss': 0.5,
 'rls': 0.75,
 'rss': 0.5,
 'rsl': 0.5,
 'rll': 0.75,
 'fls': 0.75,
 'fss': 0.5,
 'fsl': 0.5,
 'fll': 0.75,
 'pls': 0.75,
 'pss': 0.5,
 'psl': 0.5,
 'pll': 0.75,
 'bls': 0.75,
 'bss': 0.5,
 'bsl': 0.5,
 'bll': 0.75,
 'sls': 0.75,
 'sss': 0.5,
 'ssl': 0.5,
 'sll': 0.75}
LegDict = {'s': '/models/char/tt_a_chr_dgs_shorts_legs_',
           'm': '/models/char/tt_a_chr_dgm_shorts_legs_',
           'l': '/models/char/tt_a_chr_dgl_shorts_legs_'}
TorsoDict = {'s': '/models/char/dogSS_Naked-torso-',
             'm': '/models/char/dogMM_Naked-torso-',
             'l': '/models/char/dogLL_Naked-torso-',
             'ss': '/models/char/tt_a_chr_dgs_shorts_torso_',
             'ms': '/models/char/tt_a_chr_dgm_shorts_torso_',
             'ls': '/models/char/tt_a_chr_dgl_shorts_torso_',
             'sd': '/models/char/tt_a_chr_dgs_skirt_torso_',
             'md': '/models/char/tt_a_chr_dgm_skirt_torso_',
             'ld': '/models/char/tt_a_chr_dgl_skirt_torso_'}

